import { BatteryMedium, Bluetooth, Cloud, MapPin, MoreHorizontal, Phone, Plus, Radio, Smartphone, Users, Wifi } from 'lucide-react';
import { PageHeading, StatusBadge, Avatar } from '@/components/AppShell';
import { Button } from '@/components/ui/button';
import { useAppStore } from '@/stores/useAppStore';
import { deviceLabel } from '@/services/deviceService';
import { BluetoothPicker } from '@/features/bluetooth/BluetoothPicker';
import { useMemo, useState } from 'react';
import { Search } from 'lucide-react';

export function FamilyPage(){const members=useAppStore(s=>s.members);const setPage=useAppStore(s=>s.setPage);const select=useAppStore(s=>s.selectMember);const [query,setQuery]=useState('');const [filter,setFilter]=useState<'all'|'attention'|'band'|'phone'>('all');const visible=useMemo(()=>members.filter(m=>`${m.name} ${m.relation} ${m.deviceName}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='attention'&&!['safe','reunited'].includes(m.status)||filter==='band'&&m.deviceKind==='band'||filter==='phone'&&m.deviceKind==='phone')),[members,query,filter]);return <div className="page family-page"><PageHeading eyebrow="Private family circle" title="Your people & devices." copy="Searchable member details stay separate from the immersive map." action={<Button variant="violet" onClick={()=>useAppStore.getState().addSimulatedBand()}><Plus/>Add simulated band</Button>}/><div className="member-tools"><label><Search/><span className="sr-only">Search family members</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search family or device"/></label><div role="group" aria-label="Filter family members">{(['all','attention','band','phone'] as const).map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value}</button>)}</div></div><p className="member-results">Showing {visible.length} of {members.length} family members</p><section className="family-device-grid">{visible.map(m=><article key={m.id} className="family-member-card"><header><Avatar name={m.name} tone={m.status}/><button aria-label={`More options for ${m.name}`}><MoreHorizontal/></button></header><h2>{m.name}</h2><p>{m.relation}</p><StatusBadge status={m.status}/><div className="device-box"><span>{m.deviceKind==='band'?<Radio/>:<Smartphone/>}</span><div><small>{deviceLabel(m)}</small><strong>{m.deviceName}</strong><em>{m.connection}</em></div></div><dl><div><dt>Distance</dt><dd><MapPin/>{m.distance.toFixed(0)}m</dd></div><div><dt>Battery</dt><dd><BatteryMedium/>{m.battery}%</dd></div></dl><Button variant="secondary" onClick={()=>{select(m.id);setPage('map');history.pushState({},'', '/map')}}>View on map</Button></article>)}</section>{visible.length===0&&<div className="empty-alerts"><Users/><h3>No matching member.</h3><p>Try another name, device, or filter.</p></div>}<BluetoothPicker/><FamilyNetwork/></div>}

function FamilyNetwork(){return <section className="family-network"><div className="section-head"><div><p className="eyebrow"><span/> Family network</p><h2>How everyone is connected</h2></div><span className="simulation-tag">DEMO CAPABLE</span></div><div className="network-diagram"><svg viewBox="0 0 100 45" preserveAspectRatio="none"><path d="M50 22 L15 10 M50 22 L15 35 M50 22 L85 10 M50 22 L85 35"/></svg><NetworkNode className="hub" icon={<Users/>} title="Guardian" sub="This browser"/><NetworkNode className="phone" icon={<Phone/>} title="Member phone" sub="Cloud / demo"/><NetworkNode className="band1" icon={<Radio/>} title="Band 01" sub="Bluetooth"/><NetworkNode className="band2" icon={<Radio/>} title="Band 02" sub="Simulated"/><NetworkNode className="future" icon={<Wifi/>} title="Nearby" sub="Future native"/></div><div className="network-explainer"><span><Cloud/><strong>Phone sync</strong>Firebase when configured and online.</span><span><Bluetooth/><strong>Smart Band</strong>One direct BLE peripheral in supported Chrome.</span><span><Wifi/><strong>Offline phones</strong>Nearby Connections is planned for the native app.</span><span><Radio/><strong>Jury demo</strong>The complete network is safely simulated.</span></div></section>}
function NetworkNode({className,icon,title,sub}:{className:string;icon:React.ReactNode;title:string;sub:string}){return <div className={`diagram-node ${className}`}><span>{icon}</span><strong>{title}</strong><small>{sub}</small></div>}
