import { ArrowRight, BatteryMedium, Bell, Clock3, MapPin, Radio, ShieldCheck, Sparkles, Users, Wifi } from 'lucide-react';
import { motion } from 'motion/react';
import { Button } from '@/components/ui/button';
import { Avatar, NetworkStrip, PageHeading, StatusBadge } from '@/components/AppShell';
import { useAppStore } from '@/stores/useAppStore';
import { remainingTime } from '@/services/familyService';

export function HomePage() {
  const session=useAppStore(s=>s.session)!; const members=useAppStore(s=>s.members); const alerts=useAppStore(s=>s.alerts); const setPage=useAppStore(s=>s.setPage); const startDemo=useAppStore(s=>s.startDemo);
  const safe=members.filter(m=>m.status==='safe'||m.status==='reunited').length; const issue=members.length-safe;
  return <div className="page home-page"><PageHeading eyebrow="Guardian family hub" title={`Good afternoon, ${session.guardianName}.`} copy={`${session.name} is sharing privately at ${session.eventName}.`} action={<span className="session-clock"><Clock3/><span><small>SESSION REMAINING</small><strong>{remainingTime(session)}</strong></span></span>}/>
    {issue>0&&<motion.div className="alert-banner" initial={{scaleY:0}} animate={{scaleY:1}}><Bell/><div><strong>{issue} member needs your attention</strong><span>Open the live map to see the last known position.</span></div><Button variant="danger" onClick={()=>setPage('map')}>View now <ArrowRight/></Button></motion.div>}
    <section className="hero-action-card"><div><p className="eyebrow light"><span/> Live family view</p><h2>Your people.<br/>One private map.</h2><p>See who is close, who may be moving away, and guide everyone back to a familiar meeting point.</p><Button size="lg" variant="secondary" onClick={()=>setPage('map')}>Open live map <MapPin/></Button></div><FamilyRadar members={members}/></section>
    <section className="metric-row"><article><small>TOTAL FAMILY</small><strong>{members.length}</strong><span><Users/> in this session</span></article><article className="safe-metric"><small>SAFE & CLOSE</small><strong>{safe}</strong><span><ShieldCheck/> inside {session.safetyRadius}m</span></article><article><small>CONNECTED</small><strong>{members.filter(m=>m.status!=='offline').length}</strong><span><Wifi/> local / simulated</span></article><article className="sos-metric"><small>ACTIVE SOS</small><strong>{members.filter(m=>m.status==='sos').length}</strong><span><Bell/> {alerts.filter(a=>!a.resolved).length} open alerts</span></article></section>
    <div className="home-grid"><section className="members-overview"><div className="section-head"><div><p className="eyebrow"><span/> Your family</p><h2>Everyone at a glance</h2></div><button onClick={()=>setPage('family')}>Manage family <ArrowRight/></button></div><div className="member-row-list">{members.map((member)=><button key={member.id} onClick={()=>{useAppStore.getState().selectMember(member.id);setPage('map')}}><Avatar name={member.name} tone={member.status}/><span><strong>{member.name}</strong><small>{member.relation} · {member.deviceName}</small></span><span className="member-distance"><strong>{Math.round(member.distance)}m</strong><small>from guardian</small></span><BatteryMedium/><StatusBadge status={member.status}/><ArrowRight/></button>)}</div></section>
      <aside className="quick-demo"><span className="spark-box"><Sparkles/></span><p className="eyebrow"><span/> Jury walkthrough</p><h2>See the full safety story in 3 minutes.</h2><p>Watch a family move from safe to separated, raise an SOS, and reunite—all without hardware or internet.</p><Button onClick={startDemo}>Start demo story <ArrowRight/></Button><div className="demo-caption"><i/> Clearly labelled simulated experience</div></aside></div><NetworkStrip/></div>;
}

function FamilyRadar({members}:{members:ReturnType<typeof useAppStore.getState>['members']}) { return <div className="family-radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><span className="radar-center"><Radio/></span>{members.map((m,i)=><motion.span key={m.id} className={`radar-person radar-${i} status-${m.status}`} animate={{scale:[1,1.12,1]}} transition={{duration:2+i*.3,repeat:Infinity}}><i>{m.name[0]}</i><small>{m.name}</small></motion.span>)}<div className="radar-sweep"/></div>; }
