import { useEffect, useRef, useState } from 'react';
import { Bluetooth, Check, Cloud, Database, ExternalLink, Map, PauseCircle, PlayCircle, Radio, Shield, Smartphone, Trash2, WifiOff } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHeading } from '@/components/AppShell';
import { brand, productConfig } from '@/config/brand';
import { useAppStore } from '@/stores/useAppStore';
import { watchLocation, type LocationPermissionState } from '@/services/geolocationService';
import { offlineMapService } from '@/services/offlineMapService';

export function SettingsPage(){const session=useAppStore(s=>s.session)!;const mapMode=useAppStore(s=>s.mapMode);const [locationState,setLocationState]=useState<LocationPermissionState>('idle');const stopWatch=useRef<()=>void>();const [installPrompt]=useState<unknown>(null);const [offlineInstalled,setOfflineInstalled]=useState(false);const [downloadProgress,setDownloadProgress]=useState<number>();const [mapMessage,setMapMessage]=useState('');
  useEffect(()=>{offlineMapService.isInstalled().then(setOfflineInstalled);return()=>stopWatch.current?.()},[]);
  function enableLocation(){stopWatch.current=watchLocation((position)=>useAppStore.getState().addActivity(`Phone location updated with ±${Math.round(position.coords.accuracy)}m accuracy`,'location'),setLocationState)}
  return <div className="page settings-page"><PageHeading eyebrow="Privacy & settings" title="You’re in control." copy="Tracking is temporary, opt in, and visible only to this family."/><div className="settings-layout"><nav><a href="#privacy">Privacy</a><a href="#family">Family settings</a><a href="#devices">Device connections</a><a href="#map">Map & offline</a><a href="#research">Research & simulation</a><a href="#technical">Technical status</a></nav><div className="settings-sections">
    <SettingsSection id="privacy" icon={<Shield/>} title="Location privacy" copy="Only members of this private family can view shared positions. Nothing is shared with organisers or authorities by default."><div className="tracking-control"><span className={session.trackingPaused?'paused':''}><i/>{session.trackingPaused?'SHARING PAUSED':'TRACKING ACTIVE'}</span><p>{session.trackingPaused?'Cached last-known positions remain visible.':'Family members can see current and last-known locations.'}</p><Button variant={session.trackingPaused?'violet':'secondary'} onClick={()=>useAppStore.getState().toggleSharing()}>{session.trackingPaused?<PlayCircle/>:<PauseCircle/>}{session.trackingPaused?'Resume sharing':'Pause sharing'}</Button></div><div className="privacy-points"><span><Check/>Opt-in location only</span><span><Check/>Automatic event expiry</span><span><Check/>No public family maps</span></div></SettingsSection>
    <SettingsSection id="family" icon={<Radio/>} title="Family settings" copy="Choose how far a member can move before the family gets an early warning."><div className="radius-picker">{[20,50,100].map(radius=><button className={session.safetyRadius===radius?'active':''} key={radius} onClick={()=>useAppStore.setState({session:{...session,safetyRadius:radius}})}><strong>{radius}m</strong><span>{radius===20?'Very close':radius===50?'Busy venue':'Large gathering'}</span></button>)}<button><strong>Custom</strong><span>Set your own</span></button></div><p className="technical-note">Prototype timing: warning at {brand.thresholds.warningThresholdMultiplier*100}% · separation grace {brand.thresholds.separationGraceSeconds}s · stale after {brand.thresholds.staleTimeoutSeconds}s.</p></SettingsSection>
    <SettingsSection id="devices" icon={<Smartphone/>} title="This phone" copy="Browser location is never requested until you press Enable Location."><div className="permission-row"><span className={`permission-state state-${locationState}`}><i/>{locationState==='idle'?'Not requested':locationState}</span><Button onClick={enableLocation} disabled={locationState==='waiting'||locationState==='allowed'}>Enable location</Button></div><div className="capability-grid"><span><Bluetooth/><strong>Web Bluetooth</strong>{navigator.bluetooth?'Available in this browser':'Unsupported · demo fallback ready'}</span><span><Cloud/><strong>Firebase sync</strong>{productConfig.firebaseEnabled?'Configured':'Not configured · local demo storage'}</span></div></SettingsSection>
    <SettingsSection id="map" icon={<Map/>} title="Map & offline" copy="The live map uses PMTiles. Install a bounded Ramkund extract into private browser storage when a hosted archive is configured."><div className="choice-row"><button className={offlineInstalled?'active':''} disabled={!offlineMapService.isSupported()} onClick={async()=>{try{setMapMessage('Downloading bounded Ramkund archive…');await offlineMapService.download(progress=>setDownloadProgress(progress.percent));setOfflineInstalled(true);setMapMessage('Offline map installed in this browser.')}catch(error){setMapMessage(error instanceof Error?error.message:'Offline map download failed.')}}}><WifiOff/><span><strong>{offlineInstalled?'Offline area installed':'Install offline area'}</strong>{downloadProgress!==undefined?`${downloadProgress}% downloaded`:'Stored only on this device'}</span></button><button className={mapMode==='real'?'active':''} onClick={()=>useAppStore.getState().setMapMode('real')}><Map/><span><strong>PMTiles live map</strong>OSM-derived Nashik geography</span></button></div>{mapMessage&&<p className="technical-note" role="status">{mapMessage}</p>}{offlineInstalled&&<Button variant="secondary" onClick={async()=>{await offlineMapService.remove();setOfflineInstalled(false);setDownloadProgress(undefined);setMapMessage('Offline map removed from this browser.')}}>Remove offline area</Button>}<Button variant="secondary" disabled={!installPrompt}>Install application <small>{installPrompt?'Ready':'Use browser menu'}</small></Button></SettingsSection>
    <SettingsSection id="research" icon={<Database/>} title="Research & Simulation" copy="The original Command Center is a separate future infrastructure concept for large-event operators. It is not the consumer family product."><div className="research-card"><div><Radio/><span><small>LEGACY RESEARCH LAYER</small><strong>Crowd Command Center</strong></span></div><p>The original dark simulation remains unchanged and isolated from private family sessions.</p><div><Button onClick={()=>location.assign('/simulation')}>Open Command Center <ExternalLink/></Button><Button variant="secondary" onClick={()=>location.assign('/simulation?scenario=lost-child')}>Lost child scenario</Button><Button variant="secondary" onClick={()=>location.assign('/simulation?scenario=crowd-surge')}>Crowd surge</Button></div></div></SettingsSection>
    <SettingsSection id="technical" icon={<Cloud/>} title="Technical status" copy="A clear view of what is real, simulated, configured, and planned."><ul className="reality-list"><li><span className="real">REAL</span>Responsive web app, geolocation opt-in, PWA cache, MapLibre map and Web Bluetooth request flow.</li><li><span className="config">CONFIG</span>Live phone synchronization requires a Firebase project and security rules.</li><li><span className="hardware">HARDWARE</span>Real band data requires an ESP32 compatible BLE peripheral.</li><li><span className="demo">SIMULATED</span>Extra phones, bands, movement, separation, SOS and reunion in Jury Demo Mode.</li><li><span className="future-tag">FUTURE</span>Offline phone-to-phone Nearby Connections belongs in a native Android application.</li></ul></SettingsSection>
    <section className="danger-zone"><Trash2/><div><h2>End this event session</h2><p>Stops tracking and removes local session data from this browser.</p></div><Button variant="danger" onClick={()=>useAppStore.getState().endSession()}>End & delete session</Button></section>
  </div></div></div>}

function SettingsSection({id,icon,title,copy,children}:{id:string;icon:React.ReactNode;title:string;copy:string;children:React.ReactNode}){return <section className="settings-section" id={id}><header><span>{icon}</span><div><h2>{title}</h2><p>{copy}</p></div></header>{children}</section>}
